"""
Five benchmark tasks for the GridForge sealed-test evaluation.

Each task is a small dataclass that records:
  - a stable identifier (used as leaderboard column)
  - a one-line description
  - the metric(s) reported on the test split
  - whether higher or lower scores are better (for ranking)

Task definitions are intentionally lightweight; the `Baseline.predict`
methods + the `runner.run_benchmark` driver carry the actual evaluation
logic. This keeps task definitions usable as references in papers and
external submissions without requiring the rest of the benchmark
infrastructure.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Task:
    """One benchmark task."""

    name: str
    description: str
    headline_metric: str  # the metric used to rank submissions
    higher_is_better: bool  # for the headline metric
    secondary_metrics: tuple[str, ...] = ()


# ---------------------------------------------------------------------------
# T1 — 60-day failure prediction
# ---------------------------------------------------------------------------
#
# Given 30 days of monitoring leading up to t_now, predict the probability
# that cumulative damage will exceed a threshold within the next 60 days.
# (Damage threshold is a benchmark-defined "near-failure" proxy because
# our synthetic dataset's failure-mode parameters at typical loading do
# not produce hard failures within the 5-year horizon.)
#
# Headline metric: Brier score (lower is better)
# Secondary    : AUC-PR (higher is better)

T1_FAILURE_60D = Task(
    name="T1_failure_60d",
    description="60-day damage-threshold-crossing prediction from 30-day monitoring window",
    headline_metric="brier",
    higher_is_better=False,
    secondary_metrics=("auc_pr",),
)


# ---------------------------------------------------------------------------
# T2 — Remaining-useful-life regression
# ---------------------------------------------------------------------------
#
# Given the cable's full operating history to t_now, predict the time (in
# years) until cumulative damage reaches a benchmark-defined threshold.
# Cables that never reach the threshold within the simulated horizon are
# right-censored and excluded from the test split for the headline metric.
#
# Headline metric: MAE in years (lower is better)
# Secondary    : RMSE, quantile loss at q=0.5 (median)

T2_RUL_REGRESSION = Task(
    name="T2_rul_regression",
    description="Time-to-damage-threshold regression from full-history features",
    headline_metric="mae",
    higher_is_better=False,
    secondary_metrics=("rmse", "quantile_50"),
)


# ---------------------------------------------------------------------------
# T3 — Per-day anomaly detection
# ---------------------------------------------------------------------------
#
# Per-day binary anomaly classification. Ground-truth positives are days
# with a known stress event in the synthetic generator (impulse hours
# from accelerated_dielectric, sustained-overheat days from thermal_ageing).
# Healthy and water_ingress modes have no positive ground truth.
#
# Headline metric: Precision at recall = 0.9 (higher is better)
# Secondary    : AUC-PR

T3_ANOMALY = Task(
    name="T3_anomaly",
    description="Daily anomaly detection — impulse hours and sustained-overheat days as positives",
    headline_metric="precision_at_recall_0.9",
    higher_is_better=True,
    secondary_metrics=("auc_pr",),
)


# ---------------------------------------------------------------------------
# T4 — Virtual-sensor temperature prediction
# ---------------------------------------------------------------------------
#
# Given (current, ambient, soil_rho_t) at each hour, predict the conductor
# temperature. This is the surrogate-model task — exactly what the GridForge
# PINN is trained for. The IEC 60287 oracle gets close to perfect because
# the synthetic data was generated by the same equation; a gradient-boosted
# tree on engineered features is the realistic ML competitor.
#
# Headline metric: RMSE in degC (lower is better)
# Secondary    : MAE

T4_VIRTUAL_SENSOR = Task(
    name="T4_virtual_sensor",
    description="Conductor-temperature prediction from (I, ambient, soil_rho_t) at each hour",
    headline_metric="rmse",
    higher_is_better=False,
    secondary_metrics=("mae",),
)


# ---------------------------------------------------------------------------
# T5 — Counterfactual fault attribution
# ---------------------------------------------------------------------------
#
# For each test cable, attribute the fraction of cumulative damage to each
# of (load, ambient, failure-mode driver). Ground-truth fractions are
# obtainable in the synthetic dataset by re-running the simulator with one
# driver held at its baseline; the benchmark calibrates each baseline's
# attribution against those ground-truth fractions.
#
# Headline metric: MAE on attribution fractions (lower is better)
# Secondary    : RMSE on attribution fractions

T5_COUNTERFACTUAL = Task(
    name="T5_counterfactual",
    description="Counterfactual attribution of damage fractions to load / ambient / failure-mode driver",
    headline_metric="mae",
    higher_is_better=False,
    secondary_metrics=("rmse",),
)


ALL_TASKS: tuple[Task, ...] = (
    T1_FAILURE_60D,
    T2_RUL_REGRESSION,
    T3_ANOMALY,
    T4_VIRTUAL_SENSOR,
    T5_COUNTERFACTUAL,
)
