"""
Training loop and dataset generator for the IEC 60287 surrogate PINN.

The training data is generated by the IEC 60287 oracle (`solve_steady_state`)
itself: we sample (I, ambient, rho_t) uniformly from realistic operating
ranges, run the analytical solver, and pair each sample with its oracle
conductor temperature. This is the cleanest setup for physics-informed
training: the oracle provides the "ground truth" the data loss compares
against, while the same governing equation is enforced through the
physics-residual loss path.

A held-out validation set drives early stopping and the final RMSE check
that GF-003 specifies (RMSE <= 0.5 degC on conductor temperature).
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

try:
    import torch

    _TORCH_AVAILABLE = True
except ImportError:  # pragma: no cover
    torch = None  # type: ignore[assignment]
    _TORCH_AVAILABLE = False

import numpy as np

from ..physics.cable_archetype import (
    UK_11KV_240MM2_XLPE_3CORE,
    UK_TYPICAL_INSTALLATION,
)
from ..physics.thermal import (
    CableGeometry,
    CableMaterials,
    InstallationConditions,
    solve_steady_state,
)
from .loss import (
    PhysicsConstants,
    adaptive_loss_weights,
    combined_loss,
    precompute_physics_constants,
)


def _require_torch() -> None:
    if not _TORCH_AVAILABLE:
        raise ImportError(
            "PyTorch is required for gridforge.training.train. "
            "Install with: pip install 'gridforge[ml]'"
        )


@dataclass(frozen=True)
class TrainingConfig:
    """Hyperparameters for the IEC surrogate PINN training run."""

    n_train: int = 4000
    n_val: int = 800
    n_epochs: int = 1500
    batch_size: int = 256
    learning_rate: float = 2.0e-3
    physics_weight_init: float = 1.0e-3   # start small, adapt up
    weight_update_every: int = 50
    weight_update_alpha: float = 0.9       # EMA factor
    I_range_A: tuple[float, float] = (50.0, 600.0)
    ambient_range_C: tuple[float, float] = (0.0, 25.0)
    rho_t_range_KmW: tuple[float, float] = (0.7, 2.0)
    seed: int = 42
    line_voltage_V_rms: float = 11_000.0
    sheath_loss_factor: float = 0.05


@dataclass(frozen=True)
class TrainingResult:
    """Output of a training run."""

    final_train_loss: float
    final_val_rmse_C: float
    final_physics_residual_RMS: float
    epochs_run: int
    best_val_rmse_C: float
    best_epoch: int
    history: dict[str, list[float]]


def generate_training_data(
    n_samples: int,
    cfg: TrainingConfig,
    geom: CableGeometry,
    mat: CableMaterials,
    install_template: InstallationConditions,
    seed: int,
) -> tuple[np.ndarray, np.ndarray]:
    """Sample (I, ambient, rho_t) uniformly and run the IEC oracle.

    Returns a tuple (X, y) where X has shape (n_samples, 3) and y has
    shape (n_samples, 1).
    """
    rng = np.random.default_rng(seed)
    Is = rng.uniform(*cfg.I_range_A, size=n_samples)
    ambs = rng.uniform(*cfg.ambient_range_C, size=n_samples)
    rhos = rng.uniform(*cfg.rho_t_range_KmW, size=n_samples)

    targets = np.empty(n_samples)
    for i in range(n_samples):
        install = InstallationConditions(
            burial_depth_m=install_template.burial_depth_m,
            soil_thermal_resistivity_KmW=float(rhos[i]),
            ambient_soil_temp_C=float(ambs[i]),
        )
        sol = solve_steady_state(
            current_per_phase_A=float(Is[i]),
            line_voltage_V_rms=cfg.line_voltage_V_rms,
            geom=geom,
            mat=mat,
            install=install,
            sheath_loss_factor=cfg.sheath_loss_factor,
        )
        targets[i] = sol.conductor_temp_C

    X = np.stack([Is, ambs, rhos], axis=-1)
    y = targets.reshape(-1, 1)
    return X.astype(np.float32), y.astype(np.float32)


def train_pinn(
    model,
    cfg: Optional[TrainingConfig] = None,
    geom: Optional[CableGeometry] = None,
    mat: Optional[CableMaterials] = None,
    install: Optional[InstallationConditions] = None,
    verbose: bool = True,
) -> TrainingResult:
    """Train the PINN on IEC 60287 oracle data with adaptive loss weighting."""
    _require_torch()
    if cfg is None:
        cfg = TrainingConfig()
    if geom is None or mat is None:
        geom, mat = UK_11KV_240MM2_XLPE_3CORE
    if install is None:
        install = UK_TYPICAL_INSTALLATION

    constants = precompute_physics_constants(
        geom=geom, mat=mat, install=install,
        line_voltage_V_rms=cfg.line_voltage_V_rms,
        sheath_loss_factor=cfg.sheath_loss_factor,
    )

    X_train, y_train = generate_training_data(
        cfg.n_train, cfg, geom, mat, install, seed=cfg.seed
    )
    X_val, y_val = generate_training_data(
        cfg.n_val, cfg, geom, mat, install, seed=cfg.seed + 1_000_003
    )

    Xt = torch.tensor(X_train)
    yt = torch.tensor(y_train)
    Xv = torch.tensor(X_val)
    yv = torch.tensor(y_val)

    optimiser = torch.optim.Adam(model.parameters(), lr=cfg.learning_rate)
    history: dict[str, list[float]] = {
        "epoch": [], "loss_total": [], "loss_data": [], "loss_physics": [],
        "val_rmse_C": [], "w_phys": [],
    }
    w_phys = float(cfg.physics_weight_init)
    best_val = float("inf")
    best_epoch = 0
    n_train = X_train.shape[0]

    for epoch in range(cfg.n_epochs):
        model.train()
        # Shuffle indices
        perm = torch.randperm(n_train)
        epoch_loss_total = 0.0
        epoch_loss_data = 0.0
        epoch_loss_phys = 0.0
        n_batches = 0
        for start in range(0, n_train, cfg.batch_size):
            idx = perm[start : start + cfg.batch_size]
            xb = Xt[idx]
            yb = yt[idx]

            T_pred = model(xb)
            losses = combined_loss(
                T_pred, yb, xb, constants, w_data=1.0, w_phys=w_phys
            )

            optimiser.zero_grad()
            losses["total"].backward()
            optimiser.step()

            epoch_loss_total += float(losses["total"].item())
            epoch_loss_data += float(losses["data"].item())
            epoch_loss_phys += float(losses["physics"].item())
            n_batches += 1

        # Adaptive weight update
        if (epoch + 1) % cfg.weight_update_every == 0:
            T_pred_full = model(Xt)
            losses_full = combined_loss(
                T_pred_full, yt, Xt, constants, w_data=1.0, w_phys=w_phys
            )
            w_phys = adaptive_loss_weights(
                losses_full["data"],
                losses_full["physics"],
                model.parameters(),
                alpha=cfg.weight_update_alpha,
                prev_w_phys=w_phys,
            )

        # Validation
        model.eval()
        with torch.no_grad():
            T_val_pred = model(Xv)
            val_err = (T_val_pred - yv).pow(2).mean().sqrt().item()

        history["epoch"].append(epoch + 1)
        history["loss_total"].append(epoch_loss_total / max(n_batches, 1))
        history["loss_data"].append(epoch_loss_data / max(n_batches, 1))
        history["loss_physics"].append(epoch_loss_phys / max(n_batches, 1))
        history["val_rmse_C"].append(float(val_err))
        history["w_phys"].append(float(w_phys))

        if val_err < best_val:
            best_val = float(val_err)
            best_epoch = epoch + 1

        if verbose and (epoch + 1) % 100 == 0:
            print(
                f"  epoch {epoch+1:>4}/{cfg.n_epochs}  "
                f"L_data={epoch_loss_data / max(n_batches, 1):.4e}  "
                f"L_phys={epoch_loss_phys / max(n_batches, 1):.4e}  "
                f"val RMSE={val_err:.4f} degC  "
                f"w_phys={w_phys:.3e}",
                flush=True,
            )

    # Final physics residual on val set
    model.eval()
    with torch.no_grad():
        T_val_pred = model(Xv)
        from .loss import physics_residual
        res = physics_residual(T_val_pred, Xv, constants)
        phys_rms = float(res.pow(2).mean().sqrt().item())

    return TrainingResult(
        final_train_loss=history["loss_total"][-1],
        final_val_rmse_C=history["val_rmse_C"][-1],
        final_physics_residual_RMS=phys_rms,
        epochs_run=cfg.n_epochs,
        best_val_rmse_C=best_val,
        best_epoch=best_epoch,
        history=history,
    )
